name: build-and-test-darwin
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
jobs:
  build-and-test:
    runs-on: macos-12
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - run: go version
      - run: go env

      - run: go test ./...
      - run: go build
